---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)

sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_categories <- read_csv('part_categories.csv')

```

```{r}
counties <- read_csv("counties.csv")
counties

counties %>%
  select(state, county, population, professional:production)

counties %>%
  select(state, county, population, ends_with("work"))

counties %>%
  select(state, county, population, starts_with("income"))
```

#the rename verb
```{r}
counties %>%
  count(state) %>%
  rename(num_counties = n)

counties %>%
  select(state, county, poverty_rate = poverty)
```

#using transmute
```{r}
counties %>%
  transmute(state, county, population, density=population/land_area) %>%
  filter(population > 1000000) %>%
  arrange(density)
```

#pasarle a hevia desde acá
```{r}
counties %>%
  rename(unemployment_rate = unemployment)

counties %>%
  select(state, county, contains("poverty"))
```

```{r}
counties %>%
  mutate(fraction_women = women/population)

counties %>%
  transmute(state,county, employment_rate = employed/population)
```

#joining data with dplyr
```{r}
#view(sets)
sets
themes
```

```{r}
sets %>%
  inner_join(themes, by = c("theme_id" = "id"))#parametros (dataset, variable de conexión (llave))
```

```{r}
parts
view(parts)
view(part_categories)

view_parts <- parts %>%
  inner_join(part_categories, by = c("part_cat_id" = "id"))

view(view_parts)

view_parts <- parts %>%
  inner_join(part_categories, by = c("part_cat_id" = "id"), suffix = c("_parts", "_parts_categories"))

view(view_parts)
             
```






