---
title: "Cuaderno #3"
output: html_notebook
---

#intermediate R
```{r}
3==(2+1)
"ntermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"
```
#Greater and less than, mayor o menor que

```{r}
-6 * 5 + 2 >= -10 +1
"raining" <= "table"
TRUE > FALSE
"@" <= "?"
```
#comparando vectores
```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin,facebook),nrow = 2,byrow = TRUE)
views

```

#operadores Logicos
```{r}
linkedin <= 10 & facebook ==13 #operador logico "y"
linkedin <= 10 | facebook ==13 #operador logico "o"

views >11 & views <=14

```

#sentencias de condicion 
#the if statement
```{r}
medium <- "Linkedin"
num_views <- 14

if (medium == "Linkedin") {
  print("Showing Link")
} else {
  print("Unknown medium")
}

if (num_views > 15) {
  print("You´re popular!")
} else {
  print("Try to be more visible!")
}
```

#codigo mas estructurado
```{r}
medium <- "Facebook"

if (medium == "Linkedin") {
  print("Showing Linkedin information")
} else if(medium =="Facebook") {
  print("Show Facebook information")
} else {
  print("Unknown medium")
}

```
#else if 2.0
```{r}

number <- 75
result <- ""

if (number <10) {
  if (number <5) {
    result <- "extra small"
  } else{
      result <- "small"
    }
} else if (number < 100) {
  result <- "medium"
} else {
  result <- "large"
}

print(result)
```
#loops
```{r}
speed <- 64

while (speed > 30) {
  print(paste("Your speed is", speed))
  
  if (speed >= 48) {
    print("slow down big time!")
    speed <- speed -11
  }else{
   speed <- speed -6 
  }
}

speed
```
#break
```{r}
speed <- 88
while (speed > 30) {
  print(paste("YOUR SPEED IS", speed))
  
  if (speed >48) {
    print("slow down big time!")
    speed <- speed - 11
  }else{
    print("slow down!")
    speed <- speed -6
  }
  if (speed > 80) {
    break
  }
}

speed
```
#ciclo for
```{r}
linkedin <- c(16,9,13,5,2,17,14)

for (l in linkedin) {
  print(l)
}

for (i in 1:length(linkedin)) {
  print(linkedin[i])
}
```
#lopp over a list
```{r}
nyc <- list(pop=8405837,boroughs=c("manhattan","bronx","brooklyn","queens","staten island"),capital=FALSE)

for (n in nyc) {
  print(n)
}

for (i in 1:length(nyc)) {
  if (i==2) {
    for (j in 1:length(nyc[[i]])) {
      print(nyc[[i]][j])
    }
  }else{
    print(nyc[[i]])
  }
}
```
#loop over a matrix
```{r}
views <- matrix(c(linkedin,facebook),nrow = 2,byrow = TRUE)
views

for (row in 1:nrow(views)) {
  for (col in 1:ncol(views)) {
    print(paste("on row", row,"and column", col,"contains",views[row,col]))
  }
}
```





