---
title: "Clase 2"
output: html_notebook
---


#DATA FRAMES
```{r}
mtcars

head(mtcars)
tail(mtcars)

str(mtcars)
```
```{r}
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

planets_df <- data.frame(name, type, diameter, rotation, rings)
planets_df

```

selection of data frame elements
```{r}
planets_df[1,3]
planets_df[4,]
planets_df[1:5,]
planets_df[1:5,"rotation"] #se busca por titulo de columna
planets_df[1:5,c("rotation","type")] #buscar por varios titulos

rings_vector <- planets_df$rings #$ nos devuelve los valores true de una selección
rings_vector

planets_df[rings_vector,]

subset(planets_df, subset = diameter < 1) #dataframe, condicion_de_datos=filtro
```
#ORDENAMIENTO - sorting... devuelve el indice o posicion dentro de la coleccion
```{r}
a <- c(100,10,1000)
order(a)
b<-a[order(a)]
b

positions <- order(planets_df$diameter)
positions
planets_df
planets_df[positions,"diameter"] #muestra la tabla ya ordenada en función del diametro
```

#LISTAS, puede almacenar matriz, vectores o dataframes
```{r}
my_vector <- 1:10
my_matrix <- matrix(1:9,ncol = 3)
my_df <- planets_df[1:4,]

my_list <- list(my_vector,my_matrix,my_df)
my_list
```
#nombrando una lista
```{r}
names(my_list) <- c("vector","matrix","data frame")
my_list
```

#seleccionar elementos de una lista
```{r}
my_list[[3]] #obligatoriamente debe llevar doble corchete, el numero indica el elementos que se desea consultar
```
#seleccionar un elemento dentro de un elemento
```{r}
my_list[[1]][4]
my_list[[2]][2,]
my_list[[3]][2:3,1:2]
my_list [[3]][2:3,c("rotation", "rings")]
```







