---
title: "Cuaderno #4"
output: html_notebook
---

#funciones

```{r}
pow_two <- function(x, print_info = TRUE){
  y <- x ^ 2
  
  if (print_info) {
    print(paste(x, "to the power two equals", y))
  }
  return(y)
}

result <- pow_two(3)
result
```
#function scoping
```{r}
pow_two <- function(x){
  y<-x^2
  return(y)
}

pow_two(4)
y
x
```
#R passes arguments by value
```{r}
triple <- function(x){
  x <- 3^x
  x
}

a <- 5
triple(a)
a
```
#Other type of parameters
```{r}
linkedin <- c(16,9,13,5,2,17,14)

interpret <- function(num_views){
  if (num_views > 15) {
    print("you´re popular!")
    return(num_views)
  }else{
    print("try to be more visible")
    return(0)
  }
}

interpret(linkedin[1])
interpret(20)

interpret_all <- function(views, return_sum = TRUE){
  count <- 0
  
  for (v in views) {
    count <- count +interpret(v)  
  }
  if (return_sum) {
    return (count)
  }else{
    return(NULL)
  }
}

interpret_all(linkedin)
```
#carga de paquetes en R
  #primero se deben instalar los paquetes y luego llamarlos
```{r}
library(ggplot2) #aca es donde se llama el paquete

qplot(mtcars$wt, mtcars$hp)
```
#lapply
```{r}
temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

select <- function(x){
  print(mean(x))
}

list <- lapply(temp, select)
list()

lapply(temp,min)

for (t in temp) {
  print(min(t))
}
```

#lapply y funciones anonimas
```{r}
(function(x) {3*x})(3) #se llama a la funcion con los parentesis, y no es necesario nombrar a la funcion

pioneers <- c("GAUSS:1777","BAYES:1702","PASCAL:1623","PEARSON:1857")
split <- strsplit(pioneers,split = ":") #indica que divide la cadena por medio de los dos puntos :

split_low <- lapply(split, tolower) #convierte a minuscula los elementos de la lista

split
split_low

names <- lapply(split_low,function(x){x[1]}) #con esta función seleccionamos unicamente el primer dato de cada espacio de la lista/vector
names

years <- lapply(split_low, function(x){x[2]})
years
```
#usando lapply con argumentos adicionales

```{r}
select_e <- function(x,index){
  x[index]
}

names <- lapply(split_low, select_e,1)
names

years <- lapply(split_low, select_e,2)
years
```



