---
title: "Cuaderno #5"
output: html_notebook
---

#introduction to the tidyverse

```{r}
library(gapminder)
library(dplyr) #debe invocarse a la libreria

#dplyr permite realizar filtrados o agrupaciones de datos
gapminder #debe colocarse %>% para poder acceder a las funciones de dplyr
```

#filter
```{r}
gapminder %>%
  filter(year == 1957)
```


#arrange
```{r}
gapminder %>%
  arrange(lifeExp)

gapminder %>%
  arrange(desc(lifeExp))
```

#filtering and arranging
```{r}
gapminder %>%
  filter(year == 1957) %>% #agregamos un pipe por cada filtro que se desea agregar
  arrange(desc(lifeExp))
```

#the verb mutate

```{r}
gapminder %>%
  mutate(lifeExp = 12 * lifeExp) #puede modificar una columna con el dato que se le indique

gapminder %>%
  mutate(lifeExpMonths = 12 * lifeExp) #podemos agregar columnas nuevas con esta funcion
```

#combining filter, mutate and arrange
```{r}
gapminder %>%
  filter(year == 2007) %>%
  mutate(lifeExpMonths = 12*lifeExp) %>%
  arrange(desc(lifeExpMonths))
```
```{r}
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year==1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop,y=gdpPercap)) + #primero los datos, segundo los ejes y el signo mas para decir que agregaremos algo mas
  geom_point() #aca se le indica que sera un grafico de puntos o la forma que querramos darle
  
```
#Log Scaling

```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```
#coloreando la gráfica
```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) + #plotea los puntos, pero asigna un color segun continente
  geom_point() +
  scale_x_log10()
```


```{r}
gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y =lifeExp))+
  geom_point() +
  scale_x_log10() +
  facet_wrap(~continent) #grafico por variable
```


```{r}
gapminder_1952

ggplot(gapminder, aes(x=pop, y =lifeExp))+
  geom_point() +
  scale_x_log10() +
  facet_wrap(~year) #grafico por variable
```




